/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lights.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Camera" position={[3.7, 41.09, 0.88]} rotation={[0.38, 1.27, -0.37]}>
        <PerspectiveCamera name="Camera_Orientation" makeDefault={false} far={100} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group name="Light001" position={[-12.04, 11.11, 5.9]} rotation={[1.39, -0.01, 0.99]}>
        <pointLight name="Light001_Orientation" intensity={1000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh name="Cube003" castShadow receiveShadow geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
      <mesh name="Sphere" castShadow receiveShadow geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
      <mesh name="Cylinder" castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
      <mesh name="Roman_Lamp_Replica" castShadow receiveShadow geometry={nodes.Roman_Lamp_Replica.geometry} material={materials.Roman_Lamp_Replica} />
    </group>
  )
}

useGLTF.preload('/lights.glb')
