/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

export default function InstancedModel(props) {
  const { nodes } = useGLTF('/staging.glb')
  const instances = useMemo(
    () => ({
      MatressSculpt: nodes.MatressSculpt004_1,
      Pillowleft: nodes.pillow_left004_1,
      Pillowright: nodes.pillow_right004_1,
      Sheet: nodes.sheet01004_1,
      Sheet1: nodes.sheet2004_1,
      Cube: nodes.Cube005_1,
      Cube1: nodes.Cube006_1,
      Cube2: nodes.Cube007_1,
      Cube3: nodes.Cube008_1,
      Cube4: nodes.Cube009_1,
      Cube5: nodes.Cube010_1,
      Cube6: nodes.Cube011_1,
      Cube7: nodes.Cube012_1,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/staging.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.16, 0, -3.7]}>
        <instances.MatressSculpt position={[-1.02, 0.02, 2.53]} scale={0.71} />
        <instances.Pillowleft position={[-1.02, 0.03, 2.53]} rotation={[1.67, -1.55, 0.09]} scale={-0.01} />
        <instances.Pillowright position={[-0.7, 0.46, 1.24]} rotation={[-1.5, -1.53, -3.07]} scale={-0.01} />
        <instances.Sheet position={[-1, 0.01, 1.97]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
        <instances.Sheet1 position={[-1.02, 0.02, 2.53]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
        <instances.Cube position={[-1.73, 0.02, 0]} />
        <instances.Cube1 position={[-1.73, 0.02, 0]} />
        <instances.Cube2 position={[-1.73, 0.02, 0]} />
        <instances.Cube3 position={[-1.73, 0.02, 0]} />
        <instances.Cube4 position={[-1.73, 0.02, 0]} />
        <instances.Cube5 position={[-1.73, 0.02, 0]} />
        <instances.Cube6 position={[-1.73, 0.02, 0]} />
        <instances.Cube7 position={[-1.73, 0.02, 0]} />
      </group>
      <group position={[0.67, 0, -2.95]} rotation={[0, Math.PI / 2, 0]}>
        <instances.MatressSculpt position={[-1.02, 0.02, 2.53]} scale={0.71} />
        <instances.Pillowleft position={[-1.02, 0.03, 2.53]} rotation={[1.67, -1.55, 0.09]} scale={-0.01} />
        <instances.Pillowright position={[-0.7, 0.46, 1.24]} rotation={[-1.5, -1.53, -3.07]} scale={-0.01} />
        <instances.Sheet position={[-1, 0.01, 1.97]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
        <instances.Sheet1 position={[-1.02, 0.02, 2.53]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
        <instances.Cube position={[-1.73, 0.02, 0]} />
        <instances.Cube1 position={[-1.73, 0.02, 0]} />
        <instances.Cube2 position={[-1.73, 0.02, 0]} />
        <instances.Cube3 position={[-1.73, 0.02, 0]} />
        <instances.Cube4 position={[-1.73, 0.02, 0]} />
        <instances.Cube5 position={[-1.73, 0.02, 0]} />
        <instances.Cube6 position={[-1.73, 0.02, 0]} />
        <instances.Cube7 position={[-1.73, 0.02, 0]} />
      </group>
      <group position={[4.85, 0, -0.13]}>
        <instances.MatressSculpt position={[-1.02, 0.02, 2.53]} scale={0.71} />
        <instances.Pillowleft position={[-1.02, 0.03, 2.53]} rotation={[1.67, -1.55, 0.09]} scale={-0.01} />
        <instances.Pillowright position={[-0.7, 0.46, 1.24]} rotation={[-1.5, -1.53, -3.07]} scale={-0.01} />
        <instances.Sheet position={[-1, 0.01, 1.97]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
        <instances.Sheet1 position={[-1.02, 0.02, 2.53]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
        <instances.Cube position={[-1.73, 0.02, 0]} />
        <instances.Cube1 position={[-1.73, 0.02, 0]} />
        <instances.Cube2 position={[-1.73, 0.02, 0]} />
        <instances.Cube3 position={[-1.73, 0.02, 0]} />
        <instances.Cube4 position={[-1.73, 0.02, 0]} />
        <instances.Cube5 position={[-1.73, 0.02, 0]} />
        <instances.Cube6 position={[-1.73, 0.02, 0]} />
        <instances.Cube7 position={[-1.73, 0.02, 0]} />
      </group>
      <group position={[3.09, 0.59, -1.78]} rotation={[-2.73, -1.47, 0.4]} scale={0.62}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial008.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial009.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial005.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial007.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial006.geometry} material={materials.Scutum} />
        </group>
      </group>
      <group position={[3.68, 0.63, 0.18]} rotation={[-1.74, 0.12, -1.3]} scale={0.62}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial003.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial004.geometry} material={materials.Scutum} position={[0, -0.02, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial002.geometry} material={materials.Scutum} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial001.geometry} material={materials.Scutum} />
        </group>
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Carpet.geometry} material={materials['Modelling Material.Random']} position={[1.96, 0, 1.49]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Cloth.geometry} material={materials['Modelling Material.Random.001']} position={[3.46, 3.11, 1.87]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[0.01, 0.02, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.Coin.geometry} material={materials['/mat/defaultMat']} position={[1.69, 0, -1.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_misc__S_tl1tbhnfa_LOD0.geometry} material={materials['Material.011']} position={[0.13, 0, -2.76]} rotation={[Math.PI / 2, 0, -2.49]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_clay_other_S_udtheeava_LOD0.geometry} material={materials['Material.010']} position={[2.09, 0.12, -0.95]} rotation={[-0.17, 1.06, -2.71]} scale={0.01} />
      <group position={[-0.89, 0.47, 2.06]} rotation={[-0.03, 0.02, 1.48]} scale={[0.37, 0.93, 0.93]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube034.geometry} material={materials['Musculata_01_SHADER.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube034_1.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube034_2.geometry} material={materials['Musculata_01_SHADER.002']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Sheath003.geometry} material={materials.Blade} position={[-0.15, 0.19, 2.12]} rotation={[3.03, 0.08, -2.03]} scale={0} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost001.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost003.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost004.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost005.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost007.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost008.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost009.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost010.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost011.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost012.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost015.geometry} material={materials['Modelling Material.Floor']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost016.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost017.geometry} material={materials['Modelling Material.Beams']} position={[0, 0, 0.2]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost018.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost013.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost014.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost019.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost002.geometry} material={materials['Modelling Material.Beams']} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPostDetail02.geometry} material={materials['Modelling Material.Beams']} position={[5.04, 3.24, -1.43]} scale={-0.04} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost020.geometry} material={materials['Modelling Material.Beams']} position={[-1.84, 1.62, 1.84]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost021.geometry} material={materials['Modelling Material.Beams']} position={[-1.85, 1.63, -2.93]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost022.geometry} material={materials['Modelling Material.Beams']} position={[-1.85, 1.63, -0.18]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost024.geometry} material={materials['Modelling Material.Beams']} position={[-1.85, 1.63, 3.8]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost025.geometry} material={materials['Modelling Material.Beams']} position={[0.33, 1.63, -2.93]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost026.geometry} material={materials['Modelling Material.Beams']} position={[2.41, 1.63, -2.93]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost027.geometry} material={materials['Modelling Material.Beams']} position={[2.8, 0, -5.93]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost028.geometry} material={materials['Modelling Material.Beams']} position={[4.65, 1.63, -3]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost006.geometry} material={materials['Modelling Material.Beams']} position={[4.69, 1.63, 1.85]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost023.geometry} material={materials['Modelling Material.Beams']} position={[4.69, 1.63, -0.18]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPost029.geometry} material={materials['Modelling Material.Beams']} position={[4.69, 1.63, 3.84]} />
      <mesh castShadow receiveShadow geometry={nodes.ChestBody.geometry} material={materials.Wood} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={[0.52, 0.52, 0.73]} />
      <mesh castShadow receiveShadow geometry={nodes.ChestTop.geometry} material={materials.Wood} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={[0.52, 0.52, 0.73]} />
      <mesh castShadow receiveShadow geometry={nodes.ChestBody001.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.ChestBody002.geometry} material={materials['Rusted Metal']} position={[1.14, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Torus.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.ChestTop001.geometry} material={materials.Wood} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={[0.52, 0.52, 0.73]} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere.geometry} material={materials['Rusted Metal']} position={[1.15, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere006.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={materials['Rusted Metal']} position={[0.85, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere007.geometry} material={materials['Rusted Metal']} position={[0.85, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere008.geometry} material={materials['Rusted Metal']} position={[1.14, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.ChestBody003.geometry} material={materials['Rusted Metal']} position={[0.85, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.ChestBody004.geometry} material={materials['Rusted Metal']} position={[0.85, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.ChestBody005.geometry} material={materials['Rusted Metal']} position={[1.14, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['Rusted Metal']} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.ChestTop002.geometry} material={materials.Wood} position={[1, 0.3, -2.42]} rotation={[0, -Math.PI / 2, 0]} scale={0.52} />
      <mesh castShadow receiveShadow geometry={nodes.Sella_V01_LOD_00_BezierCurve004.geometry} material={materials.Sella_V01} position={[4.44, 0, -2.41]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <group position={[4.65, 0.82, -2.23]} rotation={[3.14, 0, -2.98]} scale={[0.37, 0.93, 0.93]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube035.geometry} material={materials['Musculata_01_SHADER.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube035_1.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube035_2.geometry} material={materials['Musculata_01_SHADER.002']} />
      </group>
      <group position={[4.42, 1.33, -2.02]} rotation={[-1.79, -0.05, 0.04]} scale={0.09}>
        <mesh castShadow receiveShadow geometry={nodes.Circle_1.geometry} material={materials.Remache} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_2.geometry} material={materials.Punta} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_3.geometry} material={materials.Trapecio} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_4.geometry} material={materials.Punta_baja} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_5.geometry} material={materials.Palo} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_6.geometry} material={materials.Bola} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_7.geometry} material={materials.Cuerda} />
      </group>
      <group position={[4.3, 1.33, -1.97]} rotation={[-1.72, 0, 0.02]} scale={0.09}>
        <mesh castShadow receiveShadow geometry={nodes.Circle004.geometry} material={materials.Remache} />
        <mesh castShadow receiveShadow geometry={nodes.Circle004_1.geometry} material={materials.Punta} />
        <mesh castShadow receiveShadow geometry={nodes.Circle004_2.geometry} material={materials.Trapecio} />
        <mesh castShadow receiveShadow geometry={nodes.Circle004_3.geometry} material={materials.Punta_baja} />
        <mesh castShadow receiveShadow geometry={nodes.Circle004_4.geometry} material={materials.Palo} />
        <mesh castShadow receiveShadow geometry={nodes.Circle004_5.geometry} material={materials.Bola} />
        <mesh castShadow receiveShadow geometry={nodes.Circle004_6.geometry} material={materials.Cuerda} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Aset_bread_walnut_S_tf3nehypa_LOD1.geometry} material={materials['Material.002']} position={[4.05, 0.88, -0.59]} rotation={[Math.PI / 2, 0, -2.09]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_misc_M_tl1xfcbfa_LOD0.geometry} material={materials['/mat/Default_OBJ']} position={[4.26, 0, 0.18]} rotation={[Math.PI / 2, 0, -1.6]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Niederbieber_von_gravert001.geometry} material={materials['Musculata_01_SHADER.001']} position={[4.24, 1, 0.27]} rotation={[-0.27, -0.86, -0.28]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_misc__S_tl2qbdffa_LOD0.geometry} material={materials['Material.006']} position={[4.37, 0.82, -0.54]} rotation={[Math.PI / 2, 0, -0.89]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_misc_S_ubhgfe1jw_LOD0.geometry} material={materials['Material.007']} position={[4.3, 0.92, -0.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_misc_S_ucymdgciw_LOD0.geometry} material={materials['Material.004']} position={[4.26, 0.88, -0.13]} rotation={[Math.PI / 2, 0, -1.75]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_decorative_S_udrxdduqx_LOD0001.geometry} material={materials.Wooden_Plate_UDRXDDUQX} position={[4.06, 0.81, -0.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_decorative_S_uimjdjeiw_LOD0.geometry} material={materials['Material.003']} position={[4.41, 0.81, 0.76]} rotation={[1.58, 0, 1.46]} scale={0.03} />
      <mesh castShadow receiveShadow geometry={nodes.Roman_Lamp_Replica.geometry} material={materials.Roman_Lamp_Replica} position={[4.38, 0.82, 1.2]} rotation={[0, 0.43, 0]} scale={0.06} />
      <mesh castShadow receiveShadow geometry={nodes.Gladius003001.geometry} material={materials.Blade} position={[4.47, 1.05, 0.38]} rotation={[0.12, 0.28, 1.16]} scale={0} />
      <mesh castShadow receiveShadow geometry={nodes.Sheath003001.geometry} material={materials.Blade} position={[4.06, 0.83, 0.91]} rotation={[-3.11, 1.42, 3.11]} scale={0} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_window_M_vmgjfabdw_LOD0.geometry} material={materials['default_material.001']} position={[-1.98, 0.89, -1.31]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_window_M_vmgjfabdw_LOD0001.geometry} material={materials['default_material.001']} position={[-1.98, 0.89, 2.9]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_window_M_vmgjfabdw_LOD0002.geometry} material={materials['default_material.001']} position={[-0.79, 0.89, -3.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_window_M_vmgjfabdw_LOD0003.geometry} material={materials['default_material.001']} position={[3.45, 0.89, -3.18]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_window_M_vmhmaardw_LOD0.geometry} material={materials['default_material.003']} position={[1.34, 1.15, -3.08]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_building_window_M_vmhmaardw_LOD0001.geometry} material={materials['default_material.003']} position={[-1.84, 1.15, 0.8]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0, 0, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.Niederbieber_von_gravert.geometry} material={materials['Musculata_01_SHADER.001']} position={[-1.44, 0.89, 0.71]} rotation={[-2.67, 1.31, 2.65]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_misc_S_tllkdiejw_LOD0.geometry} material={materials['Material.005']} position={[-1.22, 0.75, 0.72]} rotation={[Math.PI / 2, 0, -1.06]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Aset_wood_decorative_S_udrxdduqx_LOD0.geometry} material={materials.Wooden_Plate_UDRXDDUQX} position={[-1.24, 0, 0.63]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Roman_Lamp_Replica001.geometry} material={materials.Roman_Lamp_Replica} position={[-1.3, 0.74, 0.5]} rotation={[-Math.PI, -0.85, -Math.PI]} scale={0.06} />
      <mesh castShadow receiveShadow geometry={nodes.Stool_Aset_interior_furniture_M_vevhfe3bw_LOD0.geometry} material={materials.default_material} position={[-1.35, 0, 0.64]} rotation={[Math.PI / 2, 0, -2.7]} scale={0.02} />
      <mesh castShadow receiveShadow geometry={nodes.Gladius003.geometry} material={materials.Blade} position={[-0.93, 0.24, 0.73]} rotation={[-0.02, -0.21, 1.93]} scale={0} />
      <instances.MatressSculpt position={[-1.02, 0.02, 2.53]} scale={0.71} />
      <instances.Pillowleft position={[-1.02, 0.03, 2.53]} rotation={[1.67, -1.55, 0.09]} scale={-0.01} />
      <instances.Pillowright position={[-0.7, 0.46, 1.24]} rotation={[-1.5, -1.53, -3.07]} scale={-0.01} />
      <instances.Sheet position={[-1, 0.01, 1.97]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
      <instances.Sheet1 position={[-1.02, 0.02, 2.53]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-0.01} />
      <instances.Cube position={[-1.73, 0.02, 0]} />
      <instances.Cube1 position={[-1.73, 0.02, 0]} />
      <instances.Cube2 position={[-1.73, 0.02, 0]} />
      <instances.Cube3 position={[-1.73, 0.02, 0]} />
      <instances.Cube4 position={[-1.73, 0.02, 0]} />
      <instances.Cube5 position={[-1.73, 0.02, 0]} />
      <instances.Cube6 position={[-1.73, 0.02, 0]} />
      <instances.Cube7 position={[-1.73, 0.02, 0]} />
    </group>
  )
}

useGLTF.preload('/staging.glb')
